version: '3.4'

services:
  customerservice:
    image: ${DOCKER_REGISTRY-}customerservice
    build:
      context: .
      dockerfile: CustomerService/Dockerfile
    depends_on:
      - mongo    

  mongo:
    image: mongo
    restart: always
    ports:
      - 4444:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081